//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class affdata
    {
        public int id { get; set; }
        public int islog_id { get; set; }
        public string afftable { get; set; }
        public int affid { get; set; }
    
        public virtual islog islog { get; set; }
    }
}
