//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class saleshistory
    {
        public int id { get; set; }
        public System.DateTime saldat { get; set; }
        public decimal mitbeg { get; set; }
        public decimal mitend { get; set; }
        public decimal salqty { get; set; }
        public int nozzle_id { get; set; }
        public int salessummary_id { get; set; }
        public string creby { get; set; }
        public System.DateTime cretime { get; set; }
        public string chgby { get; set; }
        public Nullable<System.DateTime> chgtime { get; set; }
    
        public virtual nozzle nozzle { get; set; }
        public virtual salessummary salessummary { get; set; }
    }
}
