//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class salessummary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public salessummary()
        {
            this.dother = new HashSet<dother>();
            this.saleshistory = new HashSet<saleshistory>();
        }
    
        public int id { get; set; }
        public System.DateTime saldat { get; set; }
        public string stkcod { get; set; }
        public decimal dtest { get; set; }
        public decimal ddisc { get; set; }
        public decimal purvat { get; set; }
        public int pricelist_id { get; set; }
        public int shiftsales_id { get; set; }
        public string creby { get; set; }
        public System.DateTime cretime { get; set; }
        public string chgby { get; set; }
        public Nullable<System.DateTime> chgtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dother> dother { get; set; }
        public virtual pricelist pricelist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saleshistory> saleshistory { get; set; }
        public virtual shiftsales shiftsales { get; set; }
    }
}
