//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class xpumpsecureEntities : DbContext
    {
        public xpumpsecureEntities()
            : base("name=xpumpsecureEntities")
        {
        }
        
        public xpumpsecureEntities(string connection_string)
            : base(connection_string)
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<affdata> affdata { get; set; }
        public virtual DbSet<islog> islog { get; set; }
        public virtual DbSet<scacclv> scacclv { get; set; }
        public virtual DbSet<scmodul> scmodul { get; set; }
    }
}
