//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class aptrn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aptrn()
        {
            this.stcrd = new HashSet<stcrd>();
        }
    
        public int id { get; set; }
        public string docnum { get; set; }
        public System.DateTime docdat { get; set; }
        public string vatnum { get; set; }
        public Nullable<System.DateTime> vatdat { get; set; }
        public decimal vatrat { get; set; }
        public int apmas_id { get; set; }
    
        public virtual apmas apmas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stcrd> stcrd { get; set; }
    }
}
