//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class arrcpcq
    {
        public int id { get; set; }
        public string rcpnum { get; set; }
        public string cardnum { get; set; }
        public string chqnum { get; set; }
        public decimal rcvamt { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> chgdat { get; set; }
        public int artrn_id { get; set; }
        public Nullable<int> bank_id { get; set; }
        public int rcv_method_id { get; set; }
    
        public virtual artrn artrn { get; set; }
        public virtual istab istab { get; set; }
        public virtual istab istab1 { get; set; }
    }
}
