//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dother
    {
        public int id { get; set; }
        public decimal qty { get; set; }
        public int istab_id { get; set; }
        public Nullable<int> salessummary_id { get; set; }
        public Nullable<int> dayend_id { get; set; }
        public int section_id { get; set; }
        public string creby { get; set; }
        public System.DateTime cretime { get; set; }
        public string chgby { get; set; }
        public Nullable<System.DateTime> chgtime { get; set; }
    
        public virtual dayend dayend { get; set; }
        public virtual istab istab { get; set; }
        public virtual salessummary salessummary { get; set; }
        public virtual section section { get; set; }
    }
}
