//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class islog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public islog()
        {
            this.affdata = new HashSet<affdata>();
        }
    
        public int id { get; set; }
        public string logcode { get; set; }
        public string expressdata { get; set; }
        public string xpumpdata { get; set; }
        public string xpumpuser { get; set; }
        public string module { get; set; }
        public string docnum { get; set; }
        public string description { get; set; }
        public System.DateTime cretime { get; set; }
        public string username { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affdata> affdata { get; set; }
    }
}
