//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class salessummary
    {
        public int id { get; set; }
        public System.DateTime saldat { get; set; }
        public decimal total { get; set; }
        public decimal dtest { get; set; }
        public decimal dother { get; set; }
        public decimal totqty { get; set; }
        public decimal totval { get; set; }
        public decimal ddisc { get; set; }
        public decimal netval { get; set; }
        public decimal salvat { get; set; }
        public decimal purvat { get; set; }
        public int shift_id { get; set; }
        public int stmas_id { get; set; }
        public int pricetag_id { get; set; }
    
        public virtual pricetag pricetag { get; set; }
        public virtual shift shift { get; set; }
        public virtual stmas stmas { get; set; }
    }
}
