//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class saleshistory
    {
        public int id { get; set; }
        public System.DateTime saldat { get; set; }
        public decimal mitbeg { get; set; }
        public decimal mitend { get; set; }
        public decimal salqty { get; set; }
        public decimal salval { get; set; }
        public int shift_id { get; set; }
        public int nozzle_id { get; set; }
        public int stmas_id { get; set; }
        public int pricelist_id { get; set; }
    
        public virtual nozzle nozzle { get; set; }
        public virtual pricelist pricelist { get; set; }
        public virtual shift shift { get; set; }
        public virtual stmas stmas { get; set; }
    }
}
