//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class scacclv
    {
        public int id { get; set; }
        public string username { get; set; }
        public string datacod { get; set; }
        public int scmodul_id { get; set; }
        public string read { get; set; }
        public string add { get; set; }
        public string edit { get; set; }
        public string delete { get; set; }
        public string print { get; set; }
        public string approve { get; set; }
    
        public virtual scmodul scmodul { get; set; }
    }
}
