//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class settings
    {
        public int id { get; set; }
        public string express_data_path { get; set; }
        public string orgname { get; set; }
        public string shiftprintmet { get; set; }
        public string shiftauthlev { get; set; }
        public string dayprintmet { get; set; }
        public string dayauthlev { get; set; }
        public string chgby { get; set; }
        public Nullable<System.DateTime> chgtime { get; set; }
    }
}
