//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stcrd
    {
        public int id { get; set; }
        public decimal trnqty { get; set; }
        public decimal trnval { get; set; }
        public decimal vatamt { get; set; }
        public int aptrn_id { get; set; }
        public int section_id { get; set; }
        public int shift_id { get; set; }
    
        public virtual aptrn aptrn { get; set; }
        public virtual section section { get; set; }
        public virtual shift shift { get; set; }
    }
}
