//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sttak
    {
        public int id { get; set; }
        public System.DateTime takdat { get; set; }
        public decimal qty { get; set; }
        public int shiftsales_id { get; set; }
        public int section_id { get; set; }
    
        public virtual section section { get; set; }
        public virtual shiftsales shiftsales { get; set; }
    }
}
