//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPump.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tanksetup
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int section_id { get; set; }
        public int stmas_id { get; set; }
        public int nozzle_id { get; set; }
        public bool isactive { get; set; }
    
        public virtual nozzle nozzle { get; set; }
        public virtual section section { get; set; }
        public virtual stmas stmas { get; set; }
    }
}
